### ISSUE TITLE
拒绝好友请求后显示“删除好友”

### ISSUE THREAD

**Issue by zhongyi-tong** [htcAP/FduHangoutCli#4]
![cache_-204e2bc95cc53390](https://cloud.githubusercontent.com/assets/7262715/8301277/2611348e-19bf-11e5-9579-0d0536e9adc1.jpg)

**Comment by zhongyi-tong** [comment]
然后我查了数据库发现已经成为了好友，是接口调用错了还是我写错了？

**Comment by PhoenixHe-NV** [comment]
https://github.com/htcAP/FduHangoutCli/commit/eddad5464f2dac9da8d097b87f03c03d8710debd
